-- Estrutura para registrar mesclagens de lojas/medidores sem apagar o historico.
CREATE TABLE IF NOT EXISTS public."MERGE_MEDIDORES" (
    "ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UnidadeID" bigint NOT NULL,
    "LojaPrincipalID" bigint NOT NULL,
    "LojaMescladaID" bigint NOT NULL,
    "DataInicio" date NOT NULL,
    "DataFim" date NULL,
    "MedidorUnificado" numeric NOT NULL,
    "Status" text NOT NULL DEFAULT 'Ativa',
    CONSTRAINT merge_medidores_lojas_diferentes CHECK ("LojaPrincipalID" <> "LojaMescladaID"),
    CONSTRAINT merge_medidores_status_check CHECK ("Status" IN ('Ativa', 'Desfeita'))
);

CREATE INDEX IF NOT EXISTS idx_merge_medidores_unidade
    ON public."MERGE_MEDIDORES" ("UnidadeID");

CREATE INDEX IF NOT EXISTS idx_merge_medidores_lojas
    ON public."MERGE_MEDIDORES" ("LojaPrincipalID", "LojaMescladaID");
